version: "3.8"

services:
  backend:
    build: .
    ports:
      - "4000:5713"
    environment:
      - MONGO_URI=${MONGOOSE_URL}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: